name: "YCP CS Development Environment Setup Guides"
description: "This page contains guides to aid in the setup of the development environments required for many of the YCP CS courses."

url: "https://ycpcs.github.io/dev-env-setup-guide"


kramdown:
    input: GFM
    hard_wrap: false
gems:
    - jekyll-coffeescript
    - jekyll-paginate
